services:
  discord-embedder:
    build:
      context: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_APPLICATION_ID: ${DISCORD_APPLICATION_ID}
      HOST: ${HOST}
    ports:
      - "8080:8080"
    volumes:
      - ./cookies:/app/cookies
      - ./files:/app/files
    container_name: discord-embedder
    restart: unless-stopped