services:
  discord-embedder:
    build:
      context: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_APPLICATION_ID: ${DISCORD_APPLICATION_ID}
    container_name: discord-embedder
    restart: unless-stopped