package cookies

import (
	"bytes"
	"context"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"trev.zip/llc/discord-embedder/internal/config"
)

func TestSites(t *testing.T) {
	want := []string{"instagram.com", "reddit.com", "tiktok.com", "x.com"}
	if got := Sites(); !reflect.DeepEqual(got, want) {
		t.Errorf("Sites() = %q, want %q", got, want)
	}
}

func TestSite(t *testing.T) {
	tests := []struct {
		name    string
		url     string
		want    string
		wantErr bool
	}{
		{name: "www", url: "https://www.tiktok.com/@user/video/1", want: "tiktok.com"},
		{name: "short link", url: "https://vm.tiktok.com/abc/", want: "tiktok.com"},
		{name: "uppercase", url: "https://WWW.Reddit.com/r/videos", want: "reddit.com"},
		{name: "twitter", url: "https://twitter.com/user/status/1", want: "x.com"},
		{name: "x", url: "https://x.com/user/status/1", want: "x.com"},
		{name: "unsupported", url: "https://www.youtube.com/watch?v=1", wantErr: true},
		{name: "lookalike", url: "https://nottiktok.com/video", wantErr: true},
		{name: "no host", url: "/video", wantErr: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := Site(tt.url)
			if (err != nil) != tt.wantErr {
				t.Fatalf("Site() error = %v, wantErr %v", err, tt.wantErr)
			}
			if got != tt.want {
				t.Errorf("Site() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestParse(t *testing.T) {
	tests := []struct {
		name    string
		data    string
		want    []cookie
		wantErr bool
	}{
		{
			name: "keeps supported cookies",
			data: "# Netscape HTTP Cookie File\r\n" +
				"# This file is generated by a browser extension\r\n" +
				"\r\n" +
				".tiktok.com\tTRUE\t/\tTRUE\t0\tsessionid\tsecret\r\n" +
				"#HttpOnly_www.reddit.com\tFALSE\t/\tTRUE\t0\treddit_session\ttoken\r\n" +
				".twitter.com\tTRUE\t/\tTRUE\t0\tauth_token\ttoken\r\n" +
				".example.com\tTRUE\t/\tTRUE\t0\tsessionid\tother\r\n" +
				".nottiktok.com\tTRUE\t/\tTRUE\t0\tsessionid\tother\r\n",
			want: []cookie{
				{line: ".tiktok.com\tTRUE\t/\tTRUE\t0\tsessionid\tsecret", site: "tiktok.com"},
				{line: "#HttpOnly_www.reddit.com\tFALSE\t/\tTRUE\t0\treddit_session\ttoken", site: "reddit.com"},
				{line: ".twitter.com\tTRUE\t/\tTRUE\t0\tauth_token\ttoken", site: "x.com"},
			},
		},
		{
			name: "short header",
			data: "# HTTP Cookie File\ntiktok.com\tFALSE\t/\tTRUE\t0\tsessionid\tsecret\n",
			want: []cookie{{line: "tiktok.com\tFALSE\t/\tTRUE\t0\tsessionid\tsecret", site: "tiktok.com"}},
		},
		{
			name: "only unsupported cookies",
			data: "# Netscape HTTP Cookie File\n.example.com\tTRUE\t/\tTRUE\t0\tsessionid\tother\n",
		},
		{
			name:    "json",
			data:    `[{"domain": ".tiktok.com", "name": "sessionid", "value": "secret"}]`,
			wantErr: true,
		},
		{
			name:    "missing header",
			data:    ".tiktok.com\tTRUE\t/\tTRUE\t0\tsessionid\tsecret\n",
			wantErr: true,
		},
		{
			name:    "empty",
			data:    "\n\n",
			wantErr: true,
		},
		{
			name:    "invalid cookie",
			data:    "# Netscape HTTP Cookie File\n.tiktok.com\tTRUE\t/\tsessionid\tsecret\n",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := parse([]byte(tt.data))
			if (err != nil) != tt.wantErr {
				t.Fatalf("parse() error = %v, wantErr %v", err, tt.wantErr)
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("parse() = %q, want %q", got, tt.want)
			}
		})
	}
}

func testContext(t *testing.T, cookiesDir string) context.Context {
	t.Helper()

	return config.WithConfig(context.Background(), &config.Config{
		CookiesDir: cookiesDir,
		CookiesKey: bytes.Repeat([]byte{7}, 32),
	})
}

func TestSaveAndLoad(t *testing.T) {
	cookiesDir := t.TempDir()
	ctx := testContext(t, cookiesDir)
	userID := "669341931415011378"
	path := filepath.Join(cookiesDir, userID+".txt")

	saved, err := Load(ctx, userID, "tiktok.com")
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}
	if saved != nil {
		t.Errorf("Load() = %q before saving, want nil", saved)
	}

	// First upload saves only supported sites
	sites, err := Save(ctx, userID, []byte("# Netscape HTTP Cookie File\n"+
		".tiktok.com\tTRUE\t/\tTRUE\t0\tsessionid\told\n"+
		".reddit.com\tTRUE\t/\tTRUE\t0\treddit_session\tkept\n"+
		".example.com\tTRUE\t/\tTRUE\t0\tsessionid\tdropped\n"))
	if err != nil {
		t.Fatalf("Save() error = %v", err)
	}
	if want := []string{"reddit.com", "tiktok.com"}; !reflect.DeepEqual(sites, want) {
		t.Errorf("Save() = %q, want %q", sites, want)
	}

	// Second upload replaces TikTok and keeps Reddit
	sites, err = Save(ctx, userID, []byte("# Netscape HTTP Cookie File\n"+
		".www.tiktok.com\tTRUE\t/\tTRUE\t0\tsessionid\tnew\n"+
		".x.com\tTRUE\t/\tTRUE\t0\tauth_token\tadded\n"))
	if err != nil {
		t.Fatalf("Save() error = %v", err)
	}
	if want := []string{"tiktok.com", "x.com"}; !reflect.DeepEqual(sites, want) {
		t.Errorf("Save() = %q, want %q", sites, want)
	}

	want := "# Netscape HTTP Cookie File\n" +
		".reddit.com\tTRUE\t/\tTRUE\t0\treddit_session\tkept\n" +
		".www.tiktok.com\tTRUE\t/\tTRUE\t0\tsessionid\tnew\n" +
		".x.com\tTRUE\t/\tTRUE\t0\tauth_token\tadded\n"
	for _, site := range []string{"tiktok.com", "reddit.com", "x.com"} {
		if saved, err = Load(ctx, userID, site); err != nil || string(saved) != want {
			t.Errorf("Load(%q) = %q, %v, want %q", site, saved, err, want)
		}
	}
	if saved, err = Load(ctx, userID, "instagram.com"); err != nil || saved != nil {
		t.Errorf("Load() for unsaved site = %q, %v, want no cookies", saved, err)
	}
	if saved, err = Load(ctx, "other-user", "tiktok.com"); err != nil || saved != nil {
		t.Errorf("Load() for other user = %q, %v, want no cookies", saved, err)
	}

	// The file on disk is encrypted
	encrypted, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	for _, secret := range []string{"Netscape", "sessionid", "reddit_session", "kept", "new"} {
		if bytes.Contains(encrypted, []byte(secret)) {
			t.Errorf("saved cookies contain plaintext %q", secret)
		}
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if perm := info.Mode().Perm(); perm != 0600 {
		t.Errorf("cookies file permissions = %o, want 600", perm)
	}
	entries, err := os.ReadDir(cookiesDir)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 1 {
		t.Errorf("cookies dir has %d entries, want 1", len(entries))
	}
}

func TestLoadRejectsOtherUsersFile(t *testing.T) {
	cookiesDir := t.TempDir()
	ctx := testContext(t, cookiesDir)
	data := []byte("# Netscape HTTP Cookie File\n.tiktok.com\tTRUE\t/\tTRUE\t0\tsessionid\tsecret\n")

	if _, err := Save(ctx, "alice", data); err != nil {
		t.Fatal(err)
	}
	if err := os.Rename(filepath.Join(cookiesDir, "alice.txt"), filepath.Join(cookiesDir, "mallory.txt")); err != nil {
		t.Fatal(err)
	}

	if _, err := Load(ctx, "mallory", "tiktok.com"); !errors.Is(err, errDecrypt) {
		t.Errorf("Load() error = %v, want errDecrypt", err)
	}
}

func TestSaveReplacesUndecryptableCookies(t *testing.T) {
	cookiesDir := t.TempDir()
	data := []byte("# Netscape HTTP Cookie File\n.tiktok.com\tTRUE\t/\tTRUE\t0\tsessionid\tsecret\n")

	if _, err := Save(testContext(t, cookiesDir), "user", data); err != nil {
		t.Fatal(err)
	}

	// A new key cannot read the old file, so saving replaces it
	ctx := config.WithConfig(context.Background(), &config.Config{
		CookiesDir: cookiesDir,
		CookiesKey: bytes.Repeat([]byte{8}, 32),
	})
	if _, err := Load(ctx, "user", "tiktok.com"); !errors.Is(err, errDecrypt) {
		t.Fatalf("Load() with new key error = %v, want errDecrypt", err)
	}
	if _, err := Save(ctx, "user", data); err != nil {
		t.Fatalf("Save() with new key error = %v", err)
	}
	if saved, err := Load(ctx, "user", "tiktok.com"); err != nil || saved == nil {
		t.Errorf("Load() after replacing = %q, %v, want cookies", saved, err)
	}
}

func TestDisabledWithoutKey(t *testing.T) {
	ctx := config.WithConfig(context.Background(), &config.Config{CookiesDir: t.TempDir()})
	data := []byte("# Netscape HTTP Cookie File\n.tiktok.com\tTRUE\t/\tTRUE\t0\tsessionid\tsecret\n")

	if Enabled(ctx) {
		t.Error("Enabled() = true without a key")
	}
	if _, err := Save(ctx, "user", data); !errors.Is(err, ErrDisabled) {
		t.Errorf("Save() error = %v, want ErrDisabled", err)
	}
	if _, err := Load(ctx, "user", "tiktok.com"); !errors.Is(err, ErrDisabled) {
		t.Errorf("Load() error = %v, want ErrDisabled", err)
	}
}

func TestSaveWithoutSupportedCookies(t *testing.T) {
	ctx := testContext(t, t.TempDir())

	_, err := Save(ctx, "user", []byte("# Netscape HTTP Cookie File\n.example.com\tTRUE\t/\tTRUE\t0\tsessionid\tother\n"))
	if err == nil || !strings.Contains(err.Error(), "tiktok.com") {
		t.Errorf("Save() error = %v, want it to list supported sites", err)
	}
}

func TestSaveRejectsUnsafeUserIDs(t *testing.T) {
	ctx := testContext(t, t.TempDir())
	data := []byte("# Netscape HTTP Cookie File\n.tiktok.com\tTRUE\t/\tTRUE\t0\tsessionid\tsecret\n")

	for _, userID := range []string{"", ".", "..", "../user", `user\other`} {
		if _, err := Save(ctx, userID, data); err == nil {
			t.Errorf("Save() with user ID %q expected error", userID)
		}
	}
}
