name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@956a5db88619ed000a8bedc5e863353e11848021 # v1.29.0
        with:
          fetch_depth: 0
          shell: release

      - name: Run flake-release
        run: flake-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: ghcr.io
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
